### ISSUE TITLE
Disappointed

### ISSUE THREAD

**Issue by GoldenPheonix** [GovernmentOfficial/Lord-Hackysack#1]
There isn't enough meme commands. I'm disappointed in you Goverment.

**Comment by GoldenPheonix** [comment]
BUMP

**Comment by GovernmentOfficial** [comment]
soo are you here to suggest or shitpost on my github?

If you want to suggest meme commands dm me 👌

**Comment by GoldenPheonix** [comment]
A little bit of both really :3

**Comment by GovernmentOfficial** [comment]
Suggest in dms then 🤦‍♂️

**Comment by GoldenPheonix** [comment]
closed?

**Comment by GoldenPheonix** [comment]
u can't shut me down
